#ARDUINO_DIR            = arduino
#TARGET                 = sketch1
TARGET                 = leoTestharnes.pde
#ARDUINO_LIBS           =
#MCU                    = atmega32u4
#F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
#AVRDUDE_ARD_BAUDRATE   = 115200
#AVRDUDE_ARD_PROGRAMMER = arduino

BOARD_TAG    		= leonardo

#include arduino/Arduino.mk
#ARDUINO_VERSION = 150


   ARDUINO_DIR   = Arduino
   ARDMK_DIR     = ~/projects/arduino/Arduino-Makefile
   AVR_TOOLS_DIR = /usr
   ARDUINO_LIBS	 = PinChangeInt #cppfix MemoryFree Arduino-PID-Library/PID_v1 RCArduinoFastLib#ByteBuffer  cbiface GetPSTR  


include ~/projects/arduino/Arduino-Makefile/arduino-mk/Arduino.mk
#include Arduino/Arduino.mk
